// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: query.sql

package superdb

import (
	"context"
	"database/sql"
)

const createPlayers = `-- name: CreatePlayers :one
INSERT INTO teams (
  name,
  ground
) VALUES (
  $1, $2
) RETURNING team_id, name, ground, created_at
`

type CreatePlayersParams struct {
	Name   sql.NullString `json:"name"`
	Ground sql.NullString `json:"ground"`
}

func (q *Queries) CreatePlayers(ctx context.Context, arg CreatePlayersParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, createPlayers, arg.Name, arg.Ground)
	var i Team
	err := row.Scan(
		&i.TeamID,
		&i.Name,
		&i.Ground,
		&i.CreatedAt,
	)
	return i, err
}
